[package]
name = 'calculator_l05'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
metaschool = "0x21dec4c1dbdd4a789716ca219a862b2740694750cbe891ac1c6b1176f14f2c00"
std = "0x1"